/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCameraRouteImport } from './routes/api/camera'
import { Route as ApiDailyDotjsonRouteImport } from './routes/api/daily[.]json'
import { Route as ApiLiveDotjsonRouteImport } from './routes/api/live[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraRoute = ApiCameraRouteImport.update({
  id: '/api/camera',
  path: '/api/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyDotjsonRoute = ApiDailyDotjsonRouteImport.update({
  id: '/api/daily.json',
  path: '/api/daily.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveDotjsonRoute = ApiLiveDotjsonRouteImport.update({
  id: '/api/live.json',
  path: '/api/live.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/camera': typeof ApiCameraRoute
  '/api/daily.json': typeof ApiDailyDotjsonRoute
  '/api/live.json': typeof ApiLiveDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/camera': typeof ApiCameraRoute
  '/api/daily.json': typeof ApiDailyDotjsonRoute
  '/api/live.json': typeof ApiLiveDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/camera': typeof ApiCameraRoute
  '/api/daily.json': typeof ApiDailyDotjsonRoute
  '/api/live.json': typeof ApiLiveDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/camera' | '/api/daily.json' | '/api/live.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/camera' | '/api/daily.json' | '/api/live.json'
  id: '__root__' | '/' | '/api/camera' | '/api/daily.json' | '/api/live.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCameraRoute: typeof ApiCameraRoute
  ApiDailyDotjsonRoute: typeof ApiDailyDotjsonRoute
  ApiLiveDotjsonRoute: typeof ApiLiveDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera': {
      id: '/api/camera'
      path: '/api/camera'
      fullPath: '/api/camera'
      preLoaderRoute: typeof ApiCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily.json': {
      id: '/api/daily.json'
      path: '/api/daily.json'
      fullPath: '/api/daily.json'
      preLoaderRoute: typeof ApiDailyDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live.json': {
      id: '/api/live.json'
      path: '/api/live.json'
      fullPath: '/api/live.json'
      preLoaderRoute: typeof ApiLiveDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCameraRoute: ApiCameraRoute,
  ApiDailyDotjsonRoute: ApiDailyDotjsonRoute,
  ApiLiveDotjsonRoute: ApiLiveDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
